# Generated by Django 2.2.10 on 2022-09-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_order_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='approval'),
        ),
    ]
