# Generated by Django 2.2.10 on 2022-09-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approval',
            field=models.BooleanField(null=True),
        ),
    ]
