# Generated by Django 2.2.10 on 2022-09-05 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_payment_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(117440513)]),
        ),
    ]
