# Generated by Django 2.2.10 on 2022-09-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20220905_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='cleaning_date',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street',
            new_name='residence_name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street_number',
            new_name='ward',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='sub_county',
            field=models.CharField(default=-1.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.FloatField(default=10),
        ),
    ]
