# Generated by Django 2.2.10 on 2022-09-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20220907_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='approval'),
        ),
    ]
