# Generated by Django 2.2.10 on 2022-09-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_remove_payment_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='approval'),
        ),
    ]
