# Generated by Django 2.2.10 on 2022-09-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_payment_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='approval',
        ),
    ]
