# Generated by Django 2.2.10 on 2022-09-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_payment_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
