# Generated by Django 2.2.10 on 2022-09-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_auto_20220928_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='approval'),
        ),
    ]
