# Generated by Django 4.1.4 on 2022-12-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_equipment_alter_inventoryaccount_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentassignment',
            name='tallied',
            field=models.BooleanField(default=False),
        ),
    ]
