# Generated by Django 2.2.10 on 2022-09-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('checkout', '0001_initial'),
        ('account', '0002_email_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('carts', '0001_initial'),
        ('cleaning_tasks', '0001_initial'),
        ('products', '0003_auto_20220903_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
